### ISSUE TITLE
dataset file is missing in the github

### ISSUE THREAD

**Issue by mamanso** [aflah02/SRGAN-from-Scratch-PyTorch#1]
When open the code, you can see that in the header the code importa from dataset the MyImageFolder class. 
Where is the file containing the class?

**Comment by aflah02** [comment]
Hi!
So I wrote this code by following along the video cited in the reference and it's almost a replica of the same. My intention wasn't to train the model but just practice my pytorch skills and hence I didn't add the dataset file. It's discussed in the video here - https://youtu.be/7FO9qDOhRCc?t=1775 and the code is here - https://github.com/aladdinpersson/Machine-Learning-Collection/blob/master/ML/Pytorch/GANs/SRGAN/dataset.py
